// General

document.querySelectorAll('input[placeholder|="Diarrhea"').forEach(item => { item.value = '0'; item.dispatchEvent(new Event('input')) })
document.querySelectorAll('input[placeholder|="Vomiting (NMPA)"').forEach(item => { item.value = '0'; item.dispatchEvent(new Event('input')) })
document.querySelectorAll('input[placeholder|="Vomiting (NIH)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Anorexia (NMPA/NIH)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Nausea (NMPA/NIH)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Myalgia (NMPA/NIH)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Cough (NMPA/NIH)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Fatigue/ weakness (NMPA/NIH)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Dyspnea (NMPA/NIH)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Acute allergic reaction (NMPA/NIH)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Mucocutaneous disorder (NMPA)"').forEach(item => { item.click() })
document.querySelectorAll('input[placeholder|="Mucocutaneous disorder (NIH)"').forEach(item => { item.click() })
document.querySelectorAll('.el-select-dropdown__list > li:first-child').forEach(item => item.click())